version_label: "0.1"
preprocessing:
  CONTINENTE_MAP:
      "ESTADOS UNIDOS DE AMERICA": "America"
      "CANADA": "America"
      "BRASIL": "America"
      "ALEMANIA": "Europa"
      "FRANCIA": "Europa"
      "REINO UNIDO": "Europa"
      "ESPAÑA": "Europa"
      "CHINA": "Asia"
      "JAPON": "Asia"
  LOW_VAR_THRESHOLD: 0.01
  HIGH_CORR_THRESHOLD: 0.95
prepare:
  train_split: 0.80
  seed: 42
  files:
    - path: "consolidado_exportaciones_pais.csv"
      subcategoria_col: "Categoria"
    - path: "consolidado_exportacionestotalcategoria.csv"
      subcategoria_col: "SubCategoria"
    - path: "consolidado_consumodeagavetotal.csv"
      subcategoria_col: "SubCategoria"
    - path: "consolidado_producciontotaltequila.csv"
      subcategoria_col: "SubCategoria"
preprocess:
  target: "Valor"
  low_var: 0.01
  high_corr: 0.95
  seed: 42
  files:
    - file_name: "exportaciones_pais"
      subcategoria_col: "Categoria"
    - file_name: "exportacionestotalcategoria"
      subcategoria_col: "SubCategoria"
    - file_name: "consumodeagavetotal"
      subcategoria_col: "SubCategoria"
    - file_name: "producciontotaltequila"
      subcategoria_col: "SubCategoria"
wf_train_and_predict:
  walking_forward:
    window_size: 36
    predict_window: 1
  months_to_predict: 84
  low_var: 0.01
  high_corr: 0.95
  export_graphs: true
  files:
    - "exportaciones_pais"
    - "exportacionestotalcategoria"
    - "consumodeagavetotal"
    - "producciontotaltequila"
mlflow:
  run_name: "Run for {model}"
  experiment_name: "TequilaExportaciones"
  tracking_uri: "http://127.0.0.1:5000"